image: Visual Studio 2017

clone_depth: 3

install:
 - dotnet restore

build_script:
  - ps: .\package.ps1

test_script: off
  
artifacts:
  - path: .\*.zip 
    
deploy:
  provider: GitHub
  auth_token:
    secure: 2bhzwda2nhlr7agSQL96Lu81Hsmxdod21jyXjEXX36DYM1d8L8bIW5hNGb5hOCL0
  draft: false
  artifact: /.*\.zip/
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
